### ISSUE TITLE
Get POIs from mwm file

### ISSUE THREAD

**Issue by adix-code** [mapsme/mwm.py#3]
Is it possible to get POIs (like all bus stations) from mwm file using this module?
Can you please provide more details about mwm format? Or where can I find how to parse the mwm file in order to filter out POIs?

**Comment by Zverik** [comment]
To provide details about mwm format is a big task, for which I don't have time.
Yes, it is possible. Just provide a path to types.txt from mapsme/omim repo and filter by type: `-t highway-bus_stop`.
